apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpmg-challenge1-application
  namespace: interviews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpmg-challenge1-application
  template:
    metadata:
      labels:
        app: kpmg-challenge1-application
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: kpmg-challenge1-application
          image: registry.gitlab.com/k8s-enabled-2019/kpmg.interviews.bajescu.com/challenge1/application
          env:
            - name: PORT
              value: "80"
            - name: DATA_API
              value: https://data.challenge1.kpmg.interviews.bajescu.com
---
apiVersion: v1
kind: Service
metadata:
  name: kpmg-challenge1-application
  namespace: interviews
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: kpmg-challenge1-application
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kpmg-challenge1-application
  namespace: interviews
spec:
  rules:
    - host: application.challenge1.kpmg.interviews.bajescu.com
      http:
        paths:
          - backend:
              serviceName: kpmg-challenge1-application
              servicePort: 80
